# Regression analysis

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using  

# Exercise 1

student_2014<-read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", header=TRUE, sep=",")
head(student_2014)
dim(student_2014)
str(student_2014)
# The data includes 7 variables and 166 students. Variables includes gender, age, attitude towards statistics and exam points.

# Exersice 2

summary(student_2014)
hist(student_2014$age)
hist(student_2014$attitude)
hist(student_2014$deep)
hist(student_2014$stra)
hist(student_2014$surf)
hist(student_2014$points)
# Most students seem to be female and quite young.Points and attitudes seem to be quite normally distributed as the variables that measure deep-/strategic- and surface approach.
# tee viela scatterplot!

# Exersice 3

fit<-lm(points~attitude+age+deep,data=student_2014)
fit
summary(fit)
# The only variable that has a statistically significant relation with exam points is the attitude-variable. Age and deep approach do not have a relation.
fit2<-lm(points~attitude, data=student_2014)
fit2
summary(fit2)


